### ISSUE TITLE
Missing PTR records for cloudscale floating IPs

### ISSUE THREAD

**Issue by 54nd20** [appuio/terraform-modules#12]
No PTR records gets configured for floating IPs configured with [module](https://github.com/appuio/terraform-modules/blob/da4dc79f40a40d2481eb8249cf4d7fe5bb583238/modules/vshn-lbaas-cloudscale/main.tf)

Can be configured using parameter [reverse_ptr](https://registry.terraform.io/providers/cloudscale-ch/cloudscale/latest/docs/resources/floating_ip#reverse_ptr)

## Acceptance Criteria

* Floating IP PTR records are configured out of the box by `vshn-lbaas-cloudscale`
* https://github.com/appuio/component-openshift4-terraform/ uses new module version by default

**Comment by simu** [comment]
Suggestions for names:

* API VIP: `api.${var.node_name_suffix}`
* Router VIP: `cname.${var.node_name_suffix}`
* NAT VIP: `egress.${var.node_name_suffix}`

**Comment by tobru** [comment]
> Router VIP: `cname.${var.node_name_suffix}`

`ingress.${var.node_name_suffix}`?

**Comment by simu** [comment]
> > Router VIP: `cname.${var.node_name_suffix}`
> 
> `ingress.${var.node_name_suffix}`?

or `apps.${var.node_name_suffix}` so it matches an existing DNS record, depends a bit on what we choose to do in [OCP-301 (internal)](https://ticket.vshn.net/browse/OCP-301)
